### ISSUE TITLE
2. ¿Hay alguien trabajando en el problema?

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#13]
Investigar si hay alguna empresa o alguien que este trabajando en el problema que nosotros planteamos para desarrollar nuestra aplicación.

**Comment by ZabdielTrejo7** [comment]
Realizando una investigación específica, reunimos información la cual da como resultado la página http://www.educo.es/ donde podemos observar la pagina www.babynotez.com y la pagina www.tokappschool.com

**Comment by ZabdielTrejo7** [comment]
Información reunida.
