### ISSUE TITLE
1. Descripción del problema 

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#18]
En este apartado el equipo dará sus propuestas para armar la descripción del problema, para tener diferentes puntos de vista.

**Comment by AndresCarrasc** [comment]
se han estado realizando modificaciones para completar las definiciones de las preguntas

**Comment by AndresCarrasc** [comment]
se agregó una plataforma de la empresa kioru que es similar a lo que estamos realizando en el proyecto

**Comment by AndresCarrasc** [comment]
esta completo el issue de descripción del problema, tienes nuevos cambio y finalicé el documento.
