### ISSUE TITLE
3.3 Objetivo

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#22]

**Comment by EssauNoe** [comment]
Se entra trabajando en definir el objetivo del proyecto

**Comment by AndresCarrasc** [comment]
si es lo que se esta definiendo finalmente

**Comment by ZabdielTrejo7** [comment]
En proceso

**Comment by gerardo1207** [comment]
el objetivo se planteo con un buen proceso
