### ISSUE TITLE
4. Elección de platafroma a trabajar

### ISSUE THREAD

**Issue by EssauNoe** [Iriving/Proyecto-Final-Noveno#24]
En este apartada vamos a buscar en que plataforma vamos a desarrollar el proyecto.

**Comment by ZabdielTrejo7** [comment]
En proceso

**Comment by gerardo1207** [comment]
pueden pasar los nombres de las plataformas, las que quedaron a elegirse

**Comment by AndresCarrasc** [comment]
es checar TWILIO que es para plataforma para SMS
* phonegap
*ionic

**Comment by AndresCarrasc** [comment]
Ya se eligió las herramientas para poder trabajar y esta completo este issue
