### ISSUE TITLE
7. Tabla de interfaces

### ISSUE THREAD

**Issue by EssauNoe** [Iriving/Proyecto-Final-Noveno#27]
Se creara la tabla para ver todas nuestras interfaces en las que estamos y vamos a trabajar

**Comment by Iriving** [comment]
En este apartado se cerrará una vez que se concluyan las interfaces de todos los módulos y se agreguen a la tabla.

**Comment by gerardo1207** [comment]
Se agregaron todas las interfaces a la tabla
