### ISSUE TITLE
Desarrollo del apartado Nosotros

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#40]
En este apartado el encargado desarrollará una interfaz para dar a conoce la misión, visión, objetivos e historia de la empresa.

**Comment by AndresCarrasc** [comment]
En unos momentos subiré la información del apartado de nosotros, el cual viene todo acerca de la empresa, visión, misión, objetivos, etc.

**Comment by AndresCarrasc** [comment]
CIERRO EL ISSUE Y LAS IMAGENES DEL APARTADO NOSOTRO ESTA DENTRO DE CODE Y EN LA CARPETA DOCS
