### ISSUE TITLE
Desarrollo del apartado beneficios

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#41]
En este apartado el encargado, tendrá que realizar una interfaz en la cual se muestren los beneficios de utilizar la plataforma edunoti.

**Comment by AndresCarrasc** [comment]
ya esta terminado la creación del apartado "beneficios"

**Comment by AndresCarrasc** [comment]
Listo, en wikis esta la información del apartado beneficios, se cierra el issue
