### ISSUE TITLE
Diseño E.R base de datos

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#45]
En este apartado el usuario tendrá que desarrollar el modelo E.R de la base de datos de todo el sitio.

**Comment by AndresCarrasc** [comment]
estaré subiendo el modelo E.R de la base de datos dentro de code y ahí mismo en la carpeta de base de datos

**Comment by AndresCarrasc** [comment]
ya esta el modelo E.R en la carpeta de base de datos y cierro el issue
