### ISSUE TITLE
Construcción en MYSQL de la base de datos

### ISSUE THREAD

**Issue by Iriving** [Iriving/Proyecto-Final-Noveno#50]
En este apartado el encargado realizará la lista de comandos para agregar las diferentes tablas y condiciones, que fueron diseñadas en el maquetado de base de datos ,  y así poder tener la base de datos sólida.

**Comment by AndresCarrasc** [comment]
subiré unas imágenes de la lista de comandos de la base de datos dentro de la carpeta base de datos

**Comment by AndresCarrasc** [comment]
ya estoy subiendo imágenes de la base de datos

**Comment by AndresCarrasc** [comment]
ya esta la base de datos en MySQL, se cierra el issue
